---------- TABLES -----------------------------------------------
DROP TABLE IF EXISTS CUSTOMER		CASCADE;
DROP TABLE IF EXISTS PLAN_OPTION	CASCADE;
DROP TABLE IF EXISTS CARD			CASCADE;
DROP TABLE IF EXISTS CALL			CASCADE;
DROP TABLE IF EXISTS USAGE			CASCADE;
DROP TABLE IF EXISTS PLAN			CASCADE;
DROP TABLE IF EXISTS BILL			CASCADE;
DROP TABLE IF EXISTS PAYMENT_HIST	CASCADE;

/* LV1 */
CREATE TABLE PLAN_OPTION(
	Option		INT,			CONSTRAINT PLAN_OPTION_pk	PRIMARY KEY (Option),	CONSTRAINT PLAN_OPTION_uq	UNIQUE (Option),
	P_rate		DECIMAL(5,2),
	P_over_rate	DECIMAL(5,2),
	P_limit		INT,
	U_rate		DECIMAL(5,2),
	U_over_rate	DECIMAL(5,2),
	U_limit		INT
);

/* LV2 */
CREATE TABLE PLAN(
	ID			INT,	CONSTRAINT PLAN_pk 			PRIMARY KEY (ID),	CONSTRAINT PLAN_uq UNIQUE (ID),
	Option		INT,	CONSTRAINT PLAN_OPTION_fk	FOREIGN KEY (Option) REFERENCES PLAN_OPTION(Option),
	Signup_date	DATE
);

/* LV3 */
CREATE TABLE CUSTOMER(
	Phone		VARCHAR(12),	CONSTRAINT CUSTOMER_pk	PRIMARY KEY (Phone),	CONSTRAINT CUSTOMER_uq UNIQUE (Phone),
	First_name	VARCHAR(100),
	Last_name	VARCHAR(100),
	Dob			DATE,
	Address		VARCHAR(50),
	Plan_ID		INT,			CONSTRAINT PLAN_fk		FOREIGN KEY (Plan_ID) REFERENCES PLAN(ID),
	Enroll_date	DATE
);

CREATE TABLE BILL(
	Plan_ID		INT,			CONSTRAINT PLAN_fk				FOREIGN KEY (Plan_ID) REFERENCES PLAN(ID),
	Start_date	DATE,			CONSTRAINT BILL_composite_pk	PRIMARY KEY (Plan_ID,Start_date),
	End_date	DATE,
	Cost		DECIMAL(15,2),
	Payment		DECIMAL(15,2),
	Paid		BOOL
);

/* LV4 */
CREATE TABLE CARD(
	ID		INT,			CONSTRAINT CARD_pk		PRIMARY KEY (ID),
	Phone	VARCHAR(12),	CONSTRAINT CUSTOMER_fk	FOREIGN KEY (Phone) REFERENCES CUSTOMER(Phone),
	Balance	DECIMAL(15,2)
);

CREATE TABLE CALL(
	Phone		VARCHAR(12),	CONSTRAINT CUSTOMER_fk			FOREIGN KEY (Phone) REFERENCES CUSTOMER(Phone),
	Start_time	TIMESTAMP,		CONSTRAINT CALL_composite_pk	PRIMARY KEY (Phone,Start_time),
	End_time	TIMESTAMP
);

CREATE TABLE USAGE(
	Phone		VARCHAR(12),	CONSTRAINT CUSTOMER_fk			FOREIGN KEY (Phone) REFERENCES CUSTOMER(Phone),
	Date_rec	DATE,			CONSTRAINT USAGE_composite_pk	PRIMARY KEY (Phone,Date_rec),
	Data_used	INT
);

/* LV5 */
CREATE TABLE PAYMENT_HIST(
	Card_id		INT,			CONSTRAINT CARD_fk						FOREIGN KEY (Card_id) REFERENCES CARD(ID),
	Date_rec	DATE,			CONSTRAINT PAYMENT_HIST_composite_pk	PRIMARY KEY (Card_id,Date_rec),
	Amount		DECIMAL(15,2)
);
